[qa_webserver]
98.93.47.44  ansible_user=Santhosh ansible_ssh_pass='sandy@21'

[app_servers]
 10.12.0.9 ansible_user=Santhosh ansible_ssh_pass='sandy@21' ansible_ssh_common_args='-o ProxyCommand="sshpass -p sandy@21 ssh -W %h:%p -o StrictHostKeyChecking=no santhosh@98.93.47.44"'

[collection_servers]
 10.12.0.8 ansible_user=ubuntu ansible_ssh_common_args=-o ProxyCommand="sshpass -e ssh -W %h:%p -o StrictHostKeyChecking=no ubuntu@98.93.47.44"

[all:vars]
 ansible_become=true
 ansible_become_method=sudo
 ansible_become_user=root
 ansible_become_pass='sandy@21'
 ansible_ssh_extra_args='-o StrictHostKeyChecking=no'



 --------------------------------------------------------------
 [fqa_webserver]
 18.209.69.186 ansible_user=ubuntu ansible_ssh_pass='Qasdseq12Qwr'

[myservers]
 10.13.0.8 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519

[all:vars]
 ansible_become=true
 ansible_become_method=sudo
 ansible_become_user=root
 ansible_become_pass='Qasdseq12Qwr'
 ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
